FROM openjdk
WORKDIR usr/lib
ADD ./target/task-management-service-0.0.1-SNAPSHOT.jar /usr/lib/task-management-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "task-management-service-0.0.1-SNAPSHOT.jar"]